Nitrite stores documents into NitriteCollection
icon:file-code-o[link="http://static.javadoc.io/org.dizitart/nitrite/{version}/org/dizitart/no2/NitriteCollection.html", window="_blank"].
NitriteCollection are analogous to a table in RDBMS. A NitriteCollection is constructed using a NitriteMap
icon:file-code-o[link="http://static.javadoc.io/org.dizitart/nitrite/{version}/org/dizitart/no2/store/NitriteMap.html", window="_blank"]
which internally maintains a counted B+ tree to store documents.

Index can be created on a NitriteCollection for faster retrieval.

Each NitriteCollection has a unique name across the database to identify it uniquely. It can be created or
opened by its name only. `db.getCollection(String name)` call opens a NitriteCollection from the database. But if
it does not exist, it will be created and returned.

A NitriteCollection is observable. Any modification to it can be listened to by an implementation of `ChangeListener`
interface. Each operation raises different events like INSERT, UPDATE, REMOVE etc.

TIP: NitriteCollection is thread-safe for concurrent use.

.Example of NitriteCollection:

[source,java]
--
include::examples/collection.adoc[]
--