= Nitrite Database

image:https://travis-ci.org/dizitart/nitrite-database.svg?branch=master["Build Status", link="https://travis-ci.org/dizitart/nitrite-database"]
image:https://coveralls.io/repos/github/dizitart/nitrite-database/badge.svg["Coverage Status", link="https://coveralls.io/github/dizitart/nitrite-database"]
image:https://badges.gitter.im/dizitart/nitrite-database.svg["Gitter", link="https://gitter.im/dizitart/nitrite-database?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge"]

**NO**sql **O**bject (*NO~2~* a.k.a Nitrite) database is an open source nosql embedded
document store written in Java. It has MongoDB like API. It supports both
in-memory and single file based persistent store powered by
http://www.h2database.com/html/mvstore.html[MVStore] engine of h2 database.

Nitrite is a server-less database ideal for desktop, mobile or small web applications.

**It features**:

* Embedded key-value/document and object store
* In-memory or single data file
* Very fast and lightweight MongoDB like API
* Indexing
* Full text search capability
* Full Android compatibility
* Observable store
* Both way replication via Nitrite DataGate server

== Getting Started

=== How To Install

To use Nitrite in any Java application, just add the below dependency:

*Maven*

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>org.dizitart</groupId>
    <artifactId>nitrite</artifactId>
    <version>{version}</version>
</dependency>
----

*Gradle*

[source,groovy,subs="verbatim,attributes"]
----
compile 'org.dizitart:nitrite:{version}'
----

<<<

=== Quick Examples

[source,java]
.Initialize Database
--
Nitrite db = Nitrite.builder()
        .compressed()
        .filePath("/tmp/test.db")
        .openOrCreate("user", "password");
--

For more options on opening a database visit <<index.adoc#create-open-database,here>>.

[source,java]
.Create a Collection
--
// Create a Nitrite Collection
NitriteCollection collection = db.getCollection("test");

// Create an Object Repository
ObjectRepository<Employee> repository = db.getRepository(Employee.class);

--

.CRUD Operations
[source,java]
--
// create a document to populate data
include::../examples/document.adoc[]

// insert the document
collection.insert(doc);

// update the document
collection.update(eq("firstName", "John"), createDocument("lastName", "Wick"));

// remove the document
collection.remove(doc);
--

[source,java]
--
// insert an object
Employee emp = new Employee();
emp.setEmpId(124589);
emp.setFirstName("John");
emp.setLastName("Doe");

repository.insert(emp);

--

Details of CRUD operations for Nitrite Collection are <<index.adoc#crud-operations,here>>, and
for Object Repository are <<index.adoc#crud-operations-2,here>>.

.Create Indices
[source,java]
--
// create document index
collection.createIndex("firstName", indexOptions(IndexType.NonUnique));
collection.createIndex("note", indexOptions(IndexType.Fulltext));

// create object index
repository.createIndex("firstName", indexOptions(IndexType.NonUnique));
--

For more details on Index operations, see <<index.adoc#indexing,here>> and <<index.adoc#indexing-2,here>>.

[source,java]
.Query a Collection
--
Cursor cursor = collection.find(
                        // and clause
                        and(
                            // firstName == John
                            eq("firstName", "John"),
                            // elements of data array is less than 4
                            elemMatch("data", lt("$", 4)),
                            // elements of fruits list has one element matching orange
                            elemMatch("fruits", regex("$", "orange")),
                            // note field contains string 'quick' using full-text index
                            text("note", "quick")
                            )
                        );

for (Document document : cursor) {
    // process the document
}

// create document by id
Document document = collection.getById(nitriteId);

// query an object repository and create the first result
Employee emp = repository.find(eq("firstName", "John"))
                         .firstOrDefault();
--

There are several find filters available for feature-rich search operations. Please head over
<<index.adoc#filter,here>>.

[source,java]
.Automatic Replication
--
// connect to a DataGate server
DataGateClient dataGateClient = new DataGateClient("http://localhost:9898")
        .withAuth("userId", "password");
DataGateSyncTemplate syncTemplate
        = new DataGateSyncTemplate(dataGateClient, "remote-collection@userId");

// create sync handle
SyncHandle syncHandle = Replicator.of(db)
        .forLocal(collection)
        // a DataGate sync template implementation
        .withSyncTemplate(syncTemplate)
        // replication attempt delay of 1 sec
        .delay(timeSpan(1, TimeUnit.SECONDS))
        // both-way replication
        .ofType(ReplicationType.BOTH_WAY)
        // sync event listener
        .withListener(new SyncEventListener() {
            @Override
            public void onSyncEvent(SyncEventData eventInfo) {

            }
        })
        .configure();

// start sync in the background using handle
syncHandle.startSync();
--

[source,java]
.Import/Export Data
--
// Export data to a file
Exporter exporter = Exporter.of(db);
exporter.exportTo(schemaFile);

//Import data from the file
Importer importer = Importer.of(db);
importer.importFrom(schemaFile);
--

== Release Notes

Release notes are available https://github.com/dizitart/nitrite-database/releases[here].

== Documentation

|===
|Reference |API

|[Document]
|https://javadoc.io/doc/org.dizitart/nitrite[JavaDoc]
|===


== Build

To build and test Nitrite

[source,bash]
--
$ git clone https://github.com/dizitart/nitrite-database.git
$ cd nitrite-database
$ ./gradlew build
--

The test suite requires mongod to be running on localhost, listening on the default port. MongoDb is required
to test replication using the DataGate server. Please run the below command to create the test user in mongo.

[source,javascript]
--
db.getSiblingDB('benchmark').createUser({user: 'bench', pwd: 'bench', roles: [{role: 'readWrite', db: 'benchmark'}, {role: 'dbAdmin', db: 'benchmark'}]})
--

The test suite also requires android sdk 24.4.1 to be installed and ANDROID_HOME environment variable to be setup
properly to test the android example.

== Support / Feedback

For issues with, questions about, or feedback talk to us at https://gitter.im/dizitart/nitrite-database[Gitter].

== Bugs / Feature Requests

Think you’ve found a bug? Want to see a new feature in the Nitrite? Please open an issue https://github.com/dizitart/nitrite-database/issues[here]. But
before you file an issue please check if it is already existing or not.

== Maintainers

* Anindya Chatterjee