= Nitrite DataGate

If you are using Nitrite Database in your applications and want to synchronize the data in
real-time across the devices, you need DataGate.

Nitrite DataGate is the replication server for Nitrite database. It comes as a separate product.
It is available as a binary distribution or as a docker image.

To get the latest binary distribution please visit the
https://github.com/dizitart/nitrite-database/releases[Release] page of Github.
The docker image is available at docker hub

[source,bash]
--
docker pull dizitart/nitrite-datagate
--

*Configuration*

DataGate server needs a MongoDb instance to run. To configure Mongo details, edit the file
*datagate.properties* inside the *conf* directory of the binary distribution and set the below
properties

[source,properties]
--
# Mongo Config
datagate.mongo.host=
datagate.mongo.port=
datagate.mongo.user=
datagate.mongo.password=
datagate.mongo.database=
--

And run the server, execute the below command from bin folder

[source,bash]
--
./datagate.sh
--

To configure and run the docker image, some details like MongoDb connection
needs to be provided. Create some docker file like below and build it for
the desired result.

[source,docker]
--
FROM dizitart/nitrite-datagate

COPY keystore.jks /

## Connection details (Replace with your own values)
ENV DATAGATE_HOST "0.0.0.0"
ENV DATAGATE_HTTP_PORT "8080"
ENV DATAGATE_HTTPS_PORT "8443"
ENV DATAGATE_MONITOR_PORT "9090"
ENV DATAGATE_KEY_STORE "keystore.jks"
ENV DATAGATE_KEY_PASSWORD "s3cret"

## Mongo connection details (Replace with your own values)
ENV DATAGATE_MONGO_HOST "192.168.0.100"
ENV DATAGATE_MONGO_PORT "2706"
ENV DATAGATE_MONGO_USER "demo"
ENV DATAGATE_MONGO_PASSWORD "demoPass"
ENV DATAGATE_MONGO_DATABASE "demo"

## Starts the server
RUN ["chmod", "+x", "./datagate.sh"]
ENTRYPOINT [ "./datagate.sh" ]
--

Once the server is up and running, access the admin portal using the url
--
 http(s)://<ip>:<port>/datagate
--
