Collections are observable by nature. Every modification to it raises
a certain event which an event listener can listen to and take appropriate
user actions if registered.

Available events are:

- Insert - triggered when a new element is inserted
- Update - triggered when an element is updated
- Remove - triggered when an element is removed
- Drop - triggered when a collection is dropped
- Close - triggered when a collection is closed

*EventListener & ChangeInfo*

Every collection change can be listened to via an event listener implementation.
An event listener implementation must be registered with a collection first,
then the context information of the collection change event will be supplied to it
via a ChangeInfo
icon:file-code-o[link="http://static.javadoc.io/org.dizitart/nitrite/{version}/org/dizitart/no2/event/ChangeInfo.html", window="_blank"]
object.

.Example
[source,java]
--
// observe any change to a NitriteCollection
collection.register(new ChangeListener() {
    @Override
    public void onChange(ChangeInfo changeInfo) {
        System.out.println("Action - " + changeInfo.getChangeType());
        System.out.println("List of affected ids:");
        for (ChangedItem item : changeInfo.getChangedItems()) {
            System.out.println("Id - " + item.getChangeType());
            System.out.println("Id - " + item.getChangeTimestamp());
            System.out.println("Id - " + item.getDocument());
        }
    }
});

// observe any change to a ObjectRepository
repository.register(new ChangeListener() {
    @Override
    public void onChange(ChangeInfo changeInfo) {
        System.out.println("Action - " + changeInfo.getChangeType());
        System.out.println("List of affected ids:");
        for (ChangedItem item : changeInfo.getChangedItems()) {
            System.out.println("Id - " + item.getChangeType());
            System.out.println("Id - " + item.getChangeTimestamp());
            System.out.println("Id - " + item.getDocument());
        }
    }
});

--

NOTE: Event listener code always executes in a background thread in a non-blocking fashion.