For ObjectRepositories there is another alternative for configuring indices,
the object type can be annotated with the indexing formation. While creating a new
ObjectRepository, Nitrite will scan the object type for indexing information
and creates if any found.

[source,java]
--
import org.dizitart.no2.collection.IndexType;
import org.dizitart.no2.index.annotations.Id;
import org.dizitart.no2.index.annotations.Index;
import org.dizitart.no2.index.annotations.Indices;


@Indices({
        @Index(value = "joinDate", type = IndexType.NonUnique),
        @Index(value = "address", type = IndexType.Fulltext),
        @Index(value = "employeeNote.text", type = IndexType.Fulltext)
})
public class Employee implements Serializable {
    @Id
    private long empId;

    private Date joinDate;

    private String address;

    private Note employeeNote;
}

public class Note {
    @Id
    private long noteId;

    private String text;
}

--

*Index in Superclass*

Generally, Nitrite only scans the immediate type for index annotations, it skips
the superclass from scan. To enable the scanning in its superclass for index annotation,
a class should be marked with `@InheritIndices`.

[source,java]
--
@Indices(
        @Index(value = "date", type = IndexType.Unique)
)
public class ParentClass {
    @Id
    public Long id;
    public Date date;
}

@InheritIndices
public class ChildClass extends ParentClass {
    public String name;
}
--