Indexes helps efficient execution of queries in Nitrite. Without indexes Nitrite
must scan all documents in a collection to find a matching document. If an index
exists for a field, Nitrite uses the index to limit the number of documents it must
scan.

NOTE: Index can be created at any time on an empty or non-empty collection.

Indexes are stored in a NitriteMap
icon:file-code-o[link="http://static.javadoc.io/org.dizitart/nitrite/{version}/org/dizitart/no2/store/NitriteMap.html", window="_blank"]
which internally maintains a counted B+ tree for persistence storage.

Nitrite supports indexes on any field or sub-field of the document in a collection,
provided

- field is not of array or collection type
- field contains value of Comparable type
- another index does not exist on the same field

NOTE: Compound index is not supported in Nitrite.

*Type of Index*

Nitrite supports 3 kinds of index:

- Unique Index
- Non-unique Index
- Full-text Index

*Create an Index*

To create an index in collections use below function

[source,java]
--
void createIndex(String field, IndexOptions indexOptions)
--

[TIP]
====
Nitrite supports indexing on embedded field also

[source,java]
--
collection.createIndex("info.age", indexOptions(IndexType.NonUnique, true));
--

====


NOTE: All indexing operation is synchronous and blocking in nature, unless
`IndexOptions.async` is set to `true`.

*Rebuild Index*

To rebuild a corrupted index call

[source,java]
--
void rebuildIndex(String field, boolean async)
--

*Drop Index*

To drop index data of a specific field call

[source,java]
--
void dropIndex(String field)
--

And to drop all indices of a collection call

[source,java]
--
void dropAllIndices()
--

*Other Index Utilities*

To check if a field is already indexed call

[source,java]
--
boolean hasIndex(String field)
--

To check if currently indexing is running on a specific field call

[source,java]
--
boolean isIndexing(String field)
--

To get list of all index information of a collection call

[source,java]
--
Collection<Index> listIndices()
--

.Example
[source,java]
--
if (!collection.hasIndex("firstName")) {
    // create a on unique index on field 'firstName'
    collection.createIndex("firstName",
                    indexOptions(IndexType.NonUnique, true));
}

// drop index on field 'lastName'
collection.dropIndex("lastName");

// rebuild index on age asynchronously
collection.rebuildIndex("age", true);

// print all index details of a collection
for(Index idx : collection.listIndices()) {
    System.out.println("Field = " + idx.getField());
    System.out.println("Index Type = " + idx.getIndexType());
}

--

*Error Scenario*

Indexing operation results in an error if:

- creating index of a field where already index exists
- rebuild index of a field which is not already indexed
- drop index of a field where indexing is already running
- drop index of a field which is not already indexed
- create full-text index of a field which does not contains string value
- any field value violates unique constraints for an unique index