NitriteMapper relies on third-party serialization libraries for Document
serialization. Those libraries heavily depend on reflection, but
reflection has its toll. In environment like Android use of reflection
degrades the performance drastically. To bypass this overhead, Nitrite
provides a mechanism called Mappable
icon:file-code-o[link="http://static.javadoc.io/org.dizitart/nitrite/{version}/org/dizitart/no2/mapper/Mappable.html", window="_blank"]
interface.

If an object is `Mappable`, Nitrite will use the implementation
to convert the object to a Document and vice versa thus bypass the reflection
overhead.

[source,java]
.Example for Mappable
--

public class Employee implements Mappable {
    private String empId;
    private String name;
    private Date joiningDate;
    private Employee boss;

    @Override
    public Document write(NitriteMapper mapper) {
        Document document = new Document();
        document.put("empId", getEmpId());
        document.put("name", getName());
        document.put("joiningDate", getJoiningDate());

        if (getBoss() != null) {
            Document bossDoc = getBoss().write(mapper);
            document.put("boss", bossDoc);
        }
        return document;
    }

    @Override
    public void read(NitriteMapper mapper, Document document) {
        if (document != null) {
            setEmpId((String) document.get("empId"));
            setName((String) document.get("name"));
            setJoiningDate((Date) document.get("joiningDate"));

            Document bossDoc = (Document) document.get("boss");
            if (bossDoc != null) {
                Employee bossEmp = new Employee();
                bossEmp.read(mapper, bossDoc);
                setBoss(bossEmp);
            }
        }
    }
}

--