Nitrite converts java objects to Document before storing it in an ObjectRepository and similarly converts the Document
back to POJO while retrieving. The conversion is seamless for the end users. This conversion is managed by a NitriteMapper
icon:file-code-o[link="http://static.javadoc.io/org.dizitart/nitrite/{version}/org/dizitart/no2/mapper/NitriteMapper.html", window="_blank"]
implementation. By default NitriteMapper uses Jackson to convert POJO to a field-value map, but a custom
implementation can be set via NitriteBuilder.

[source,java]
.Example for setting a custom NitriteMapper
--

Nitrite db = Nitrite.builder()
            .nitriteMapper(new GSONMapper())        // custom NitriteMapper
            .filePath("/tmp/test.db")
            .openOrCreate("user", "password");

--

The default NitriteMapper:

* does not allow circular reference (will throw ObjectMappingException)
* needs POJO classes to have a public parameter-less constructor
* honors fields declared as `transient`

As of 3.1.0, a jackson module can be easily registered with the default jackson mapper using
the builder.

[source,java]
.Example for registering jackson module
--

Nitrite db = Nitrite.builder()
            .registerModule(new Jdk8Module())        // register jdk8 module
            .registerModule(new JavaTimeModule())    // register java.time module
            .filePath("/tmp/test.db")
            .openOrCreate("user", "password");

--