SyncHandle
icon:file-code-o[link="http://static.javadoc.io/org.dizitart/nitrite/{version}/org/dizitart/no2/sync/SyncHandle.html", window="_blank"]
is the handler for replication job. It can be used by the application code to control
replication in various stages of application life-cycle.

*Start Replication*

[source,java]
--
syncHandle.startSync();
--

*Pause Replication*

[source,java]
--
syncHandle.pauseSync();
--

If any replicator thread is currently running, it will not be paused but the next
iteration will be paused until it has been resumed by `resumeSync()` call.

*Resume Replication*

[source,java]
--
syncHandle.resumeSync();
--

*Reset Local*

[source,java]
--
syncHandle.resetLocalWithRemote(0, 100);
--

This operation clears local collection and downloads server data. This
operation supports pagination for downloading remote data.

*Reset Remote*

[source,java]
--
syncHandle.resetRemoteWithLocal(0, 100);
--

This operation clears server data and uploads local collection data. This
operation supports pagination for uploading local data.

*Cancel Sync*

[source,java]
--
syncHandle.cancelSync();
--

This operation cancels the background replicator thread.
