[source,java]
.Initialize Database
--
Nitrite db = Nitrite.builder()
        .compressed()
        .filePath("/tmp/test.db")
        .openOrCreate("user", "password");
--

For more options on opening a database visit <<index.adoc#create-open-database,here>>.

[source,java]
.Create a Collection
--
// Create a Nitrite Collection
NitriteCollection collection = db.getCollection("test");

// Create an Object Repository
ObjectRepository<Employee> repository = db.getRepository(Employee.class);

--

.CRUD Operations
[source,java]
--
// create a document to populate data
include::../examples/document.adoc[]

// insert the document
collection.insert(doc);

// update the document
collection.update(eq("firstName", "John"), createDocument("lastName", "Wick"));

// remove the document
collection.remove(doc);
--

[source,java]
--
// insert an object
Employee emp = new Employee();
emp.setEmpId(124589);
emp.setFirstName("John");
emp.setLastName("Doe");

repository.insert(emp);

--

Details of CRUD operations for Nitrite Collection are <<index.adoc#crud-operations,here>>, and
for Object Repository are <<index.adoc#crud-operations-2,here>>.

.Create Indices
[source,java]
--
// create document index
collection.createIndex("firstName", indexOptions(IndexType.NonUnique));
collection.createIndex("note", indexOptions(IndexType.Fulltext));

// create object index
repository.createIndex("firstName", indexOptions(IndexType.NonUnique));
--

For more details on Index operations, see <<index.adoc#indexing,here>> and <<index.adoc#indexing-2,here>>.

[source,java]
.Query a Collection
--
Cursor cursor = collection.find(
                        // and clause
                        and(
                            // firstName == John
                            eq("firstName", "John"),
                            // elements of data array is less than 4
                            elemMatch("data", lt("$", 4)),
                            // elements of fruits list has one element matching orange
                            elemMatch("fruits", regex("$", "orange")),
                            // note field contains string 'quick' using full-text index
                            text("note", "quick")
                            )
                        );

for (Document document : cursor) {
    // process the document
}

// create document by id
Document document = collection.getById(nitriteId);

// query an object repository and create the first result
Employee emp = repository.find(eq("firstName", "John"))
                         .firstOrDefault();
--

There are several find filters available for feature-rich search operations. Please head over
<<index.adoc#filter,here>>.

[source,java]
.Automatic Replication
--
// create sync handle
SyncHandle syncHandle = Replicator.of(db)
                .forLocal(collection)
                // a remote replica server
                .withReplica(remoteCollection)
                // replication attempt delay of 1 sec
                .delay(timeSpan(1, TimeUnit.SECONDS))
                // both-way replication
                .ofType(ReplicationType.BOTH_WAY)
                // sync event listener
                .withListener(new SyncTestEventListener())
                .configure();

// start sync in the background using handle
syncHandle.startSync();
--

[source,java]
.Import/Export Data
--
// Export data to a file
Exporter exporter = Exporter.of(db);
exporter.exportTo(schemaFile);

//Import data from the file
Importer importer = Importer.of(db);
importer.importFrom(schemaFile);
--

and many more.

For any detail information or when in doubt please consult the http://javadoc.io/doc/org.dizitart/nitrite/[javadoc].
This is not one of those plain old vanilla javadoc, it is heavily attributed with lots of example and gotchas.

TIP: Click the icon:file-code-o[] icon next to a class name in the document to go directly to corresponding javadoc.