Projection converts a record within a cursor from one format to another.
A projection operation can also convert the document/object within a cursor into
a sub-set of document with selected fields or another object with similar fields.

.Example
[source,java]
--
Cursor cursor = collection.find(lte("birthDay", new Date()),
                sort("firstName", SortOrder.Ascending).thenLimit(0, 3));

// a document with only selected field - 'firstName' and 'lastName'
Document projection = createDocument("firstName", null)
                .put("lastName", null);
// it will return documents containing only 'firstName' and 'lastName'
RecordIterable<Document> documents = cursor.project(projection);


// it will return Employees containing every field that has been inserted
Cursor<Employee> projection = repository.find();

// it will return list of SubEmployee objects containing only some fields
// of Employee object
List<SubEmployee> subEmployeeList
                = repository.find().project(SubEmployee.class).toList();

--