Removes documents/objects from a collections.

.Remove operations for NitriteCollection
[source,java]
--
WriteResult remove(Document element)
WriteResult remove(Filter filter)
WriteResult remove(Filter filter, RemoveOptions removeOptions)
--

.Remove operations for ObjectRepository
[source,java]
--
WriteResult remove(T object)
WriteResult remove(ObjectFilter filter)
WriteResult remove(ObjectFilter filter, RemoveOptions removeOptions)
--

If the `filter` is `null`, it will remove all elements in the collection.

.Example
[source,java]
--
// removes all documents where firstName = John
collection.remove(eq("firstName", "John"));

// removes all documents
collection.remove(Filters.ALL);

// removes a single document
collection.remove(doc);

// removes all objects where firstName = John
repository.remove(eq("firstName", "John"))

// remove all objects
repository.remove(ObjectFilters.ALL);
--

*RemoveOptions*

Remove operation can be customized by `removeOptions`. It provides
below option

* JustOnce - indicates if only one document will be removed or all
of them if `filter` finds multiple documents in the collection
(default is `false`).

.Example
[source,java]
--
RemoveOptions options = new RemoveOptions();
options.setJustOne(true);

// removes first document where firstName = John
collection.remove(eq("firstName", "John"), options);

--

NOTE: A remove operation raises an *REMOVE* event.